query PageQuery($slug: String!, $locale: String!) {
  pageCollection(limit: 1, locale: $locale, where: { slug: $slug }) {
    items {
      slug
      title
      description
      components {
        json
      }
      sys {
        id
        firstPublishedAt
        publishedAt
      }
    }
  }
}
